app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))
]

base/urls.py
from django.urls import path
#from views import *
from .views import Home


app_name="base"

urlpatterns = [
    path('', Home.as_view(), name='home'),
]

base/models.py
from django.db import models

# Create your models here.

base/views.py
#from django.shortcuts import render
from django.views.generic import *

# Create your views here.
class Home(TemplateView):
    template_name = 'base/home.html'

base/templates/base/home.html
{% extends "base.html" %}
{% block titulo %}
    Home
{% endblock %}
{% block contenido %}
    <h1>Hola mundo</h1>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %}App control de combustible{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.minty.css' %}">
</head>
<body>
    <!-- Barra de navegación -->
    <div class="bs-docs-section clearfix">
        <div class="row">
            <div class="bs-component">
                {% include "parts/menu.html" %}   
            </div>
        </div>
      </div>
    {% block contenido %}
        Contenido por defecto
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/fragments/menu.html
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'base:home' %}">Home
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-sm-2" type="search" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>